apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ubuntu:20.04
        command: ["sleep","infinity"]
        resources:
          limits:
            nvidia.com/gpu: 2 # requesting 1 vGPUs
            nvidia.com/gpumem: 18000 # Each vGPU contains 3000m device memory （Optional,Integer）
        ports:
        - containerPort: 80

