# Copyright 2024 NVIDIA CORPORATION
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Run this workflow on pull requests or merge to main/dev branches
name: Build Dev Image

on:
  push:
    branches:
    - main
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Free disk space
      # https://github.com/actions/virtual-environments/issues/709
      run: |
        echo "=========original CI disk space"
        df -h
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        echo "=========after clean up, the left CI disk space"
        df -h
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
        submodules: true
        persist-credentials: false
    - name: Install Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: go.mod
    - run: go version
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1
    - name: Generating image tag
      id: runtime-tag
      run: |
        echo tag="$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
    - run: BUILD_PLATFORMS="linux/amd64" VERSION="${{ steps.runtime-tag.outputs.tag }}" make ubuntu20.04
