name: Release Helm Chart

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  helm-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # create GitHub Releases & push to gh-pages
      packages: write   # push OCI chart to GHCR

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1
        with:
          version: v3.17.0


      - name: Run chart-releaser
        uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f # v1.7.0
        with:
          charts_dir: charts
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Log in to GHCR
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push chart to GHCR (OCI)
        run: |
          REPO_LOWER=$(echo "$GITHUB_REPOSITORY_OWNER" | tr '[:upper:]' '[:lower:]')
          # Extract chart version from Chart.yaml
          CHART_VERSION=$(grep '^version:' deployments/helm/volcano-vgpu-device-plugin/Chart.yaml | awk '{print $2}')

          helm package deployments/helm/volcano-vgpu-device-plugin --destination /tmp/helm-pkg

          helm push "/tmp/helm-pkg/volcano-vgpu-device-plugin-${CHART_VERSION}.tgz" \
            "oci://ghcr.io/${REPO_LOWER}/charts"
